version: '3.8'

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - API_KEY=${API_KEY}
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: '${DOMAINS:-localhost} -> http://app:3000'
      STAGE: ${STAGE:-local}
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  https-portal-data:
